# Generated by Django 2.2.9 on 2022-09-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220905_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='desription',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='text',
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
